### ISSUE TITLE
Package name  does not correspond to the file path

### ISSUE THREAD

**Issue by LilWebDev** [VishnuSivadasVS/Advanced-HttpURLConnection#2]
hi i have this problem (Package name 'com.vishnusivadas.advanced_httpurlconnection' does not correspond to the file path 'com.test.test_android') while adding this dependencies  (implementation "com.github.VishnuSivadasVS:Advanced-HttpURLConnection:1.2")
can someone help me please. 
![1](https://user-images.githubusercontent.com/86207493/127850919-49463566-ee86-4165-a977-8739280c6498.PNG)
![2](https://user-images.githubusercontent.com/86207493/127850922-3de43fc2-31d9-4ef0-9e2f-8686b3a05cda.PNG)

**Comment by VishnuSivadasVS** [comment]
make sure you add maven { url 'https://jitpack.io' } to your root gradle file
