### ISSUE TITLE
failed to resolve com.github.VishnuSivadasVs

### ISSUE THREAD

**Issue by waltare68** [VishnuSivadasVS/Advanced-HttpURLConnection#3]
Failed to resolve: com.github.VishnuSivadasVS:Advanced-HttpURLConnection:1.2
Show in Project Structure dialog
Affected Modules: app

**Comment by VishnuSivadasVS** [comment]
make sure you add maven { url 'https://jitpack.io' } to your root gradle file,

also go to file, click invalidate cache and restart

**Comment by waltare68** [comment]
great
