### ISSUE TITLE
problem with the httpurl conn

### ISSUE THREAD

**Issue by waltare68** [VishnuSivadasVS/Advanced-HttpURLConnection#4]
did you change the time for the data gets posted

**Comment by VishnuSivadasVS** [comment]
no refer this tutorial for implementation https://www.youtube.com/watch?v=X8oD4q3XtQQ

**Comment by waltare68** [comment]
It was working fine few days ago

**Comment by VishnuSivadasVS** [comment]
Try clearing the project and then go to file > invalidate cache and restart.

**Comment by VishnuSivadasVS** [comment]
Android Studio latest version there is some updates needed.
Delete dependencyResolutionManagement from setting.gradle 
Check: https://github.com/VishnuSivadasVS/Advanced-HttpURLConnection#delete-dependencyresolutionmanagement-from-settinggradle
