### ISSUE TITLE
cannot import class

### ISSUE THREAD

**Issue by Bassuka** [VishnuSivadasVS/Advanced-HttpURLConnection#5]
i can't import the PutData class, Gradle syncs without a problem.

**Comment by AJNAV01** [comment]
same with me

**Comment by preetpadariya** [comment]
Same issue

**Comment by VishnuSivadasVS** [comment]
https://github.com/VishnuSivadasVS/Advanced-HttpURLConnection#steps-to-add-the-library-to-your-project

Refer this

**Comment by VishnuSivadasVS** [comment]
Android Studio latest version there is some updates needed.
Delete dependencyResolutionManagement from setting.gradle 
Check: https://github.com/VishnuSivadasVS/Advanced-HttpURLConnection#delete-dependencyresolutionmanagement-from-settinggradle
