### ISSUE TITLE
PutData is asking  to create a class instead of importing

### ISSUE THREAD

**Issue by preetpadariya** [VishnuSivadasVS/Advanced-HttpURLConnection#7]

**Comment by VishnuSivadasVS** [comment]
https://github.com/VishnuSivadasVS/Advanced-HttpURLConnection#steps-to-add-the-library-to-your-project

Refer this

**Comment by VishnuSivadasVS** [comment]
Android Studio latest version there is some updates needed.
Delete dependencyResolutionManagement from setting.gradle 
Check: https://github.com/VishnuSivadasVS/Advanced-HttpURLConnection#delete-dependencyresolutionmanagement-from-settinggradle
